/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.3.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as images_actions from "../images/actions";
import type * as images_mutations from "../images/mutations";
import type * as images_queries from "../images/queries";
import type * as sets_actions from "../sets/actions";
import type * as sets_mutations from "../sets/mutations";
import type * as sets_queries from "../sets/queries";
import type * as voices_actions from "../voices/actions";
import type * as voices_mutations from "../voices/mutations";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "images/actions": typeof images_actions;
  "images/mutations": typeof images_mutations;
  "images/queries": typeof images_queries;
  "sets/actions": typeof sets_actions;
  "sets/mutations": typeof sets_mutations;
  "sets/queries": typeof sets_queries;
  "voices/actions": typeof voices_actions;
  "voices/mutations": typeof voices_mutations;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
